# top level stuff you probably don't need to touch
highlighter: rogue
# markdown: rdiscount
# rdiscount:
#   extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://about.rahmanzr.com/
baseurl: /
title: Zishan Rahman
author: Zishan Rahman
description: Personal blog and resume
avatar: profile.png
email: rahmanzr@gmail.com
github: windsorbrown # username
twitter: rahmanzr78
linkedin: zishanrahman
stackoverflow: users/6175432/windsorbrown  #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
#disqus: username
google_analytics: UA-77403043-1


# needed for travis-ci build
#exclude: [vendor]

tel: +1 604 5374130
#//tel_full: tel:+440000000000
google_maps: 'https://www.google.ca/maps/place/2502-1055+Homer+St,+Vancouver,+V6B+1G3'
address: 2502-1055 Homer St.
postcode: V6B 1G3
city: Vancouver
country: Canada


# needed for travis-ci build
exclude: [vendor]
